name: build

on: [push]

jobs:

  build_debian:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Build tests
      run: make build-tests
    - name: Run tests
      run: make test

  build_macos:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Build tests
      run: make build-tests
    - name: Run tests
      run: make test
