name: C CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build (${{ matrix.name }})
    strategy:
      matrix:
        include:
          - os: macos-latest
            name: macOS (Latest)
          - os: macos-11
            name: macOS (Big Sur)
          - os: macos-10.15
            name: macOS (Catalina)
          - os: ubuntu-latest
            name: Ubuntu (Latest)
          - os: ubuntu-20.04
            name: Ubuntu 20.04
          - os: ubuntu-18.04
            name: Ubuntu 18.04

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release

  build-macos-arm:
    name: Build (macOS ARM)
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_OSX_ARCHITECTURES=arm64
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release